import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from '@/app/components/ThemeProvider';
import { Providers } from "@/app/providers";
import { useUserStore } from "@/app/stores/user";
import { getSession } from "@/app/lib/session";
import { UserProvider } from "@/app/context/UserProvider";
import { Toaster } from "@/components/ui/sonner"
import {createClient} from "@/app/utils/supabase/server";
import InitUser from "@/app/lib/store/InitUser";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Fluent - An Encrypted Web-Messenger",
    // description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const supabase = await createClient()
    const {data} = await supabase.auth.getSession();


    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
                {children}
                <Toaster position={"bottom-center"} expand richColors />
                <InitUser user={data.session?.user} />
        </ThemeProvider>
        </body>
        </html>
    );
}
